//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace barbershop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public int IDVisitor { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Service { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Services Services { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
